databases:
  - name: postgis-db
    databaseName: postgis_sample
    user: seismic_user
    plan: free

services:
  - type: web
    name: seismic-backend
    runtime: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgis-db
          property: connectionString
      - key: USGS_API_BASE_URL
        value: https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary

  - type: web
    name: seismic-frontend
    runtime: static
    buildCommand: "echo 'No build needed for static files'"
    staticPublishPath: ./frontend
    plan: free 